---
- name: Install Web Server With Handlers
  hosts: all
  become: true
  become_method: sudo
  tasks:
    - name: Install web server
      yum:
        name: httpd
        state: latest
      notify: start web server

  handlers:
    - name: start web server
      service:
        name: httpd
        state: started
        enabled: yes
